name: scrapekan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  cloud_firestore: ^4.13.6
  cloud_firestore_web: ^3.8.10
  provider: ^6.1.1
  fl_chart: ^0.65.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^10.1.0
  geolocator_web: ^2.2.0
  url_launcher: ^6.2.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.1
  mobile_scanner: ^3.5.5
  table_calendar: ^3.1.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Noto Sans Symbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf
    - family: Noto Sans Symbols 2
      fonts:
        - asset: assets/fonts/NotoSansSymbols2-Regular.ttf
